[wokwi]
version = 1
gdbServerPort = 3333
elf = "../target/riscv32imc-unknown-none-elf/release/esp32-temperature-monitor"
firmware = "../target/riscv32imc-unknown-none-elf/release/esp32-temperature-monitor"
