[package]
name = "temperature-monitor-interface"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
cucumber = "^0.20"
futures = "^0.3"

[[test]]
name = "bit_reader"
harness = false

[[test]]
name = "byte_reader"
harness = false
